### ISSUE TITLE
JSVM status

### ISSUE THREAD

**Issue by mychele** [floriandejonckheere/jsvm#2]
Hi, 
I open this issue to ask what is the JSVM status. Is it still maintained?
Besides the compilation errors that I fixed yesterday with the PR, I noticed that the link in the repo description returns a 404, and that it is not possible to access to the CVS repo listed in this page https://www.hhi.fraunhofer.de/en/departments/vca/research-groups/image-video-coding/research-topics/svc-extension-of-h264avc/jsvm-reference-software.html
Thanks for your attention,
Michele

**Comment by floriandejonckheere** [comment]
Hi

I originally set up this repo to have a git mirror of the CVS repo. I am not the maintainer of this software, nor do I have any ties to the people who wrote it. Since the CVS repo disappeared, this git repo exists simply for archival purposes and is not maintained.

Regards

Florian
